/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. */

#ifndef __GVT_COMPRESS_REGS_H__
#define __GVT_COMPRESS_REGS_H__

#include <linux/bits.h>

/*
 * Register offsets
 */
#define GVT_UDMA_TX_REGS_OFF			0x0
#define GVT_UDMA_RX_REGS_OFF			0x20000
#define GVT_UDMA_GEN_REGS_OFF			0x38000
#define GVT_UDMA_GEN_EX_REGS_OFF		0x3C000

#define GVT_UDMA_CHANGE_STATE_OFF		0x204
#define GVT_UDMA_SHADOW_ACCESS_OFF		0x700

#define GVT_UDMA_GEN_AXI_CFG_1_OFF		0x2300
#define GVT_UDMA_GEN_EX_VMPR_OFF(qid, i)	((0x40 * qid) + i)
#define GVT_UDMA_GEN_EX_VMPR_V4_OFF(qid, i)	(0x400 + (0x40 * qid) + i)

/* Compression engine */
#define GVT_COMP_REGS_OFF		0x20000
#define GVT_COMP_ICRC_PROF_OFF		0x11080
#define GVT_COMP_LZ_CFG_OFF		0x18
#define GVT_COMP_ALG_OFF		0x20
#define GVT_COMP_ENC_PROF_OFF		0x40
#define GVT_COMP_DEC_PROF_OFF		0x50
#define GVT_COMP_FMT_OFF		0x70
#define GVT_COMP_ENC_OUT_OFF		0xd0
#define GVT_COMP_HUFFMAN_TBL_OFF	0x100

#define GVT_COMP_HUFFMAN_STATIC_TABLE_NUM_ENTRIES_SMALL	286
#define GVT_COMP_HUFFMAN_STATIC_TABLE_NUM_ENTRIES_BIG	30
#define GVT_COMP_HUFFMAN_STATIC_TABLE_NUM_ENTRIES	\
			(GVT_COMP_HUFFMAN_STATIC_TABLE_NUM_ENTRIES_SMALL + \
			 GVT_COMP_HUFFMAN_STATIC_TABLE_NUM_ENTRIES_BIG)

/* Unit adapter */
#define GVT_ADAPTER_SMCC				0x110
#define GVT_ADAPTER_SMCC_CONF_2				0x114
#define GVT_ADAPTER_GENERIC_CONTROL_11			0x220
#define GVT_ADAPTER_GENERIC_CONTROL_19			0x240

#define GVT_ADAPTER_SMCC_CONF_SNOOP_OVR			BIT(0)
#define GVT_ADAPTER_SMCC_CONF_SNOOP_ENABLE		BIT(1)
#define GVT_ADAPTER_SMCC_CONF_VM_ID_IPA_OVERRIDE	BIT(14)
#define GVT_ADAPTER_SMCC_CONF_2_DIS_ERROR_TRACK		BIT(8)
#define GVT_ADAPTER_GEN_CTL_19_READ_ROB_EN		BIT(0)
#define GVT_ADAPTER_GEN_CTL_19_READ_ROB_FORCE_INORDER	BIT(1)
#define GVT_ADAPTER_GEN_CTL_19_READ_ROB_SW_RESET	BIT(15)
#define GVT_ADAPTER_GEN_CTL_19_WRITE_ROB_EN		BIT(16)
#define GVT_ADAPTER_GEN_CTL_19_WRITE_ROB_FORCE_INORDER	BIT(17)
#define GVT_ADAPTER_GEN_CTL_19_WRITE_ROB_SW_RESET	BIT(31)

#define GVT_ADAPTER_SMCC_CONF_VM_ID_SHIFT		15
#define GVT_ADAPTER_SMCC_CONF_VM_ID_MASK		0x7FFF8000

/* UDMA TX registers */
#define GVT_UDMA_TX_OSTAND_CFG_OFF		0x124
#define GVT_UDMA_TX_CFG_LEN_OFF			0x254
#define GVT_UDMA_TX_DESC_PREF_CFG_2_OFF		0x304
#define GVT_UDMA_TX_DESC_PREF_CFG_3_OFF		0x308
#define GVT_UDMA_TX_DATA_CFG_OFF		0x310
#define GVT_UDMA_TX_CFG_APPLICATION_ACK_OFF	0x408

/* UDMA RX registers */
#define GVT_UDMA_RX_OSTAND_CFG_RD_OFF		0x124
#define GVT_UDMA_RX_OSTAND_CFG_WR_OFF		0x128
#define GVT_UDMA_RX_DESC_PREF_CFG_3_OFF		0x308
#define GVT_UDMA_RX_COMP_CFG_1C_OFF		0x380
#define GVT_UDMA_RX_CFG_APPLICATION_ACK_OFF	0x38C

/* UDMA Q registers */
#define GVT_UDMA_QUEUE_REG_CFG_OFF		0x20
#define GVT_UDMA_QUEUE_REG_DRBP_LOW_OFF		0x28
#define GVT_UDMA_QUEUE_REG_DRBP_HIGH_OFF	0x2C
#define GVT_UDMA_QUEUE_REG_DRL_OFF		0x30
#define GVT_UDMA_QUEUE_REG_DRTP_INC_OFF		0x38
#define GVT_UDMA_QUEUE_REG_CRBP_LOW_OFF		0x44
#define GVT_UDMA_QUEUE_REG_CRBP_HIGH_OFF	0x48
#define GVT_UDMA_QUEUE_REG_CRHP_OFF		0x4C
#define GVT_UDMA_QUEUE_REG_RLIMIT_MASK_OFF	0x74
#define GVT_UDMA_TX_QUEUE_REG_COMP_CFG_OFF	0xA0
#define GVT_UDMA_RX_QUEUE_REG_COMP_CFG_OFF	0x54
#define GVT_UDMA_RX_QUEUE_REG_SW_CTRL_OFF	0x64

#define GVT_UDMA_QUEUE_REGS_OFF(qid)		(0x1000 + (0x1000 * qid))
#define GVT_UDMA_QUEUE_TX_SHADOW_REGS_OFF(qid)	(0x100000 + (0x10000 * qid))
#define GVT_UDMA_QUEUE_RX_SHADOW_REGS_OFF(qid)	\
		(GVT_UDMA_QUEUE_TX_SHADOW_REGS_OFF(qid) + 0x1000)

/*
 * Register fields
 */

/* UDMA TX fields */
#define GVT_UDMA_TX_DATA_CFG_DATA_FIFO_DEPTH_MASK		0x00000FFF
#define GVT_UDMA_TX_OSTAND_CFG_MAX_DATA_RD_MASK			0x000000FF
#define GVT_UDMA_TX_OSTAND_CFG_MAX_DATA_RD_SHIFT		0
#define GVT_UDMA_TX_OSTAND_CFG_MAX_DESC_RD_MASK			0x0000FF00
#define GVT_UDMA_TX_OSTAND_CFG_MAX_DESC_RD_SHIFT		8
#define GVT_UDMA_TX_OSTAND_CFG_MAX_COMP_REQ_MASK		0x00FF0000
#define GVT_UDMA_TX_OSTAND_CFG_MAX_COMP_REQ_SHIFT		16
#define GVT_UDMA_TX_CFG_LEN_MAX_PKT_SIZE_MASK			0x000FFFFF
#define GVT_UDMA_TX_CFG_LEN_MAX_PKT_SIZE_SHIFT			0
#define GVT_UDMA_TX_CFG_LEN_ENCODE_64K				BIT(24)
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_2_MAX_DESC_PER_PKT_MASK	0x00000FFF
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_2_MAX_DESC_PER_PKT_SHIFT	0
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_3_MIN_BURST_MASK		0x000000F0
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_3_MIN_BURST_SHIFT		4
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_3_PREF_THR_MASK		0x0000FF00
#define GVT_UDMA_TX_RD_DESC_PREF_CFG_3_PREF_THR_SHIFT		8

/* UDMA RX fields */
#define GVT_UDMA_RX_OSTAND_CFG_RD_MAX_DESC_RD_OSTAND_MASK	0x000000FF
#define GVT_UDMA_RX_OSTAND_CFG_RD_MAX_DESC_RD_OSTAND_SHIFT	0
#define GVT_UDMA_RX_OSTAND_CFG_WR_MAX_DATA_WR_OSTAND_MASK	0x000000FF
#define GVT_UDMA_RX_OSTAND_CFG_WR_MAX_DATA_WR_OSTAND_SHIFT	0
#define GVT_UDMA_RX_OSTAND_CFG_WR_MAX_COMP_REQ_MASK		0x00FF0000
#define GVT_UDMA_RX_OSTAND_CFG_WR_MAX_COMP_REQ_SHIFT		16
#define GVT_UDMA_RX_RD_DESC_PREF_CFG_3_MIN_BURST_MASK		0x000000F0
#define GVT_UDMA_RX_RD_DESC_PREF_CFG_3_MIN_BURST_SHIFT		4
#define GVT_UDMA_RX_RD_DESC_PREF_CFG_3_PREF_THR_MASK		0x0000FF00
#define GVT_UDMA_RX_RD_DESC_PREF_CFG_3_PREF_THR_SHIFT		8
#define GVT_UDMA_RX_COMP_CFG_1C_DESC_SIZE_MASK			0x0000000F

/* UDMA Q fields */
#define GVT_UDMA_Q_RATE_LIMIT_MASK_INTERNAL_PAUSE_DMB		BIT(2)
#define GVT_UDMA_Q_COMP_CFG_EN_COMP_RING_UPDATE			BIT(0)
#define GVT_UDMA_Q_COMP_CFG_DIS_COMP_COAL			BIT(1)
#define GVT_UDMA_Q_CFG_EN_PREF					BIT(16)
#define GVT_UDMA_Q_CFG_EN_SCHEDULING				BIT(17)

#define GVT_UDMA_RX_Q_SW_CTRL_RST_Q				BIT(8)

/*
 * SW version metric offset
 */
#define GVT_SW_VER_METRIC_OFFSET	(0x3b460)
#define GVT_SW_VER_METRIC_LEN		4

/*
 * Graviton Compression Completion Status bits
 */
/* Compression status - 00b means compression successful and
 *			11b means original copied to dest
 */
#define GVT_COMP_CMPRS_STATUS			(0x6)

/* Error check masks in word0 above */
#define GVT_COMP_AUTH_ERROR			BIT(0)
#define GVT_COMP_SA_IV_EVICT_FIFO_ERROR		BIT(8)
#define GVT_COMP_M2S_ERROR			BIT(10)
#define GVT_COMP_SRAM_PARITY_ERROR		BIT(11)
#define GVT_COMP_INTERNAL_FLOW_VIOLATION_ERROR	BIT(15)

#define GVT_COMP_ERROR_MASK	(GVT_COMP_AUTH_ERROR                    | \
				GVT_COMP_SA_IV_EVICT_FIFO_ERROR		| \
				GVT_COMP_M2S_ERROR                      | \
				GVT_COMP_SRAM_PARITY_ERROR              | \
				GVT_COMP_INTERNAL_FLOW_VIOLATION_ERROR)
#define GVT_COMP_LAST_IN_TRANSACTION_MASK	BIT(27)

/* Compress/Decompress output size masks in word1, 2 and 3 above */
#define GVT_COMP_RESULT_SIZE_CDESC_W1_MASK	(0x000f0000)
#define GVT_COMP_RESULT_SIZE_CDESC_W2_MASK	(0x0000ffff)
#define GVT_DECOMP_RESULT_SIZE_CDESC_W3_MASK	(0x000fffff)

/*
 * UDMA descriptors and completion descriptors bits
 */
#define GVT_UDMA_MAX_SRC_DESCS			(31)
#define GVT_UDMA_RING_ID_MASK			(0x3)
#define GVT_UDMA_CDESC_LAST			BIT(27)

#define GVT_UDMA_CHANGE_STATE_NORMAL		BIT(0)
#define GVT_UDMA_CHANGE_STATE_DIS		BIT(1)

#define GVT_UDMA_TX_DESC_RING_ID_SHIFT		(24)
#define GVT_UDMA_TX_DESC_RING_ID_MASK		(0x3)
#define GVT_UDMA_TX_COMP_OP			(3)
#define GVT_UDMA_TX_DESC_META_CRYPT_DIR_SHIFT	(22)
#define GVT_UDMA_TX_DESC_META_OP_SHIFT		(23)
#define GVT_UDMA_TX_DESC_META_SA_IDX_SHIFT	(5)
#define GVT_UDMA_TX_DESC_META_CMPRS_HIS_WIN_RST	BIT(13)
#define GVT_UDMA_TX_DESC_META_AUTH_VALID	BIT(14)
#define GVT_UDMA_TX_DESC_META_CRYPT_S_GET_SIGN	BIT(17)
#define GVT_UDMA_TX_DESC_META_SA_IDX_MASK	(0x7f << 5)
#define GVT_UDMA_TX_DESC_META_CRYPT_GET_ORIG	BIT(19)

#define GVT_UDMA_TX_DESC_FIRST			BIT(26)
#define GVT_UDMA_TX_DESC_LAST			BIT(27)
#define GVT_UDMA_TX_DESC_CONCAT			BIT(31)
#define GVT_UDMA_TX_DESC_LEN_MASK		(0xffff)


#define GVT_UDMA_RX_DESC_LEN_MASK		(0xffff)
#define GVT_UDMA_RX_DESC_RING_ID_SHIFT		(24)

#define GVT_CRYPT_SAD_OP_SHIFT				(29)
#define GVT_CRYPT_SAD_OP_AUTH				(BIT(2))
#define GVT_CRYPT_SAD_OP_CMPRS				(BIT(0))
#define GVT_CRYPT_SAD_AUTH_AFTER_DEC			(BIT(3))
#define GVT_CRYPT_SAD_AUTH_TYPE_SHIFT			(12)
#define GVT_CRYPT_SAD_ICRC_PROF_ID_SHIFT		(12)
#define GVT_CRYPT_SAD_CMPRS_LZ_PROF_IDX_LSBS_MASK	0xf8000000
#define GVT_CRYPT_SAD_CMPRS_LZ_PROF_IDX_LSBS_SHIFT	27
#define GVT_CRYPT_SAD_CMPRS_LZ_PROF_IDX_MSBS_SHIFT	25
#define GVT_CRYPT_SAD_CMPRS_FORCE_COMPRESSED_OUT_SHIFT	22

#endif	/* __GVT_COMPRESS_REGS_H__ */
